version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc_backend
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongo:27017}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - UNSTRUCTURED_URL=${UNSTRUCTURED_URL:-http://unstructured:8000}
      - BACKEND_CORS_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    volumes:
      - .:/app
    depends_on:
      - mongo
      - qdrant
      - redis
      - ollama
      - unstructured
    networks:
      - backend_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: doc_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: doc_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

  redis:
    image: redis:alpine
    container_name: doc_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    container_name: doc_unstructured
    restart: always
    ports:
      - "8001:8000"
    networks:
      - backend_network

  ollama:
    image: ollama/ollama:latest
    container_name: doc_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  qdrant_data:
  mongo_data:
  ollama_data:
