[tool.ruff]
line-length = 88

[tool.ruff.lint]
# Enable pycodestyle (E) and Pyflakes (F) codes by default.
select = ["E", "F", "I"]
ignore = []

# Allow autofix for all enabled rules (when `--fix` is provided).
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
